spring.application.name=flashcard
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.h2.console.enabled=true

app.jwt.secret=21966fda-4a7a-4f96-ac5c-5458b70bbc39
app.admin.username=Demo123
app.cookies.secure=false


spring.jpa.open-in-view=true
logging.level.org.springframework.web=TRACE
logging.level.sk.foxer.flashcard=DEBUG